Repository swordglowsblue/haven-json, pull requests merged in 2018-10, with the labels that each got.

#15 Rewrite String.jsonEscape() and String.jsonUnescape().
  src/main/kotlin/com/tripl3dogdare/havenjson/Utils.kt
Labels: enhancement

#14 Remove NameConverter system, replace with NamePolicy system
  README.md
  doc/haven-json/alltypes/index.html
  doc/haven-json/com.tripl3dogdare.havenjson/-custom-name-policy/convert-field-name.html
  doc/haven-json/com.tripl3dogdare.havenjson/-custom-name-policy/index.html
  doc/haven-json/com.tripl3dogdare.havenjson/-json-name-policy/-init-.html
  doc/haven-json/com.tripl3dogdare.havenjson/-json-name-policy/index.html
  doc/haven-json/com.tripl3dogdare.havenjson/-json-name-policy/nc.html
  doc/haven-json/com.tripl3dogdare.havenjson/-json-property/-init-.html
  doc/haven-json/com.tripl3dogdare.havenjson/-json-property/index.html
  doc/haven-json/com.tripl3dogdare.havenjson/-json-schema.html
  doc/haven-json/com.tripl3dogdare.havenjson/-json-value/index.html
  doc/haven-json/com.tripl3dogdare.havenjson/-name-policy/-as-written.html
  doc/haven-json/com.tripl3dogdare.havenjson/-name-policy/-camel-to-kebab.html
  doc/haven-json/com.tripl3dogdare.havenjson/-name-policy/-camel-to-pascal.html
  doc/haven-json/com.tripl3dogdare.havenjson/-name-policy/-camel-to-snake.html
  doc/haven-json/com.tripl3dogdare.havenjson/-name-policy/-custom.html
  doc/haven-json/com.tripl3dogdare.havenjson/-name-policy/-kebab-to-camel.html
  doc/haven-json/com.tripl3dogdare.havenjson/-name-policy/-kebab-to-pascal.html
  doc/haven-json/com.tripl3dogdare.havenjson/-name-policy/-kebab-to-snake.html
  doc/haven-json/com.tripl3dogdare.havenjson/-name-policy/-lowercase.html
  doc/haven-json/com.tripl3dogdare.havenjson/-name-policy/-pascal-to-camel.html
  doc/haven-json/com.tripl3dogdare.havenjson/-name-policy/-pascal-to-kebab.html
  doc/haven-json/com.tripl3dogdare.havenjson/-name-policy/-pascal-to-snake.html
  doc/haven-json/com.tripl3dogdare.havenjson/-name-policy/-snake-to-camel.html
  doc/haven-json/com.tripl3dogdare.havenjson/-name-policy/-snake-to-kebab.html
  doc/haven-json/com.tripl3dogdare.havenjson/-name-policy/-snake-to-pascal.html
  doc/haven-json/com.tripl3dogdare.havenjson/-name-policy/-uppercase.html
  doc/haven-json/com.tripl3dogdare.havenjson/-name-policy/get-declared-name-policies.html
  doc/haven-json/com.tripl3dogdare.havenjson/-name-policy/get-name-converter.html
  doc/haven-json/com.tripl3dogdare.havenjson/-name-policy/index.html
  doc/haven-json/com.tripl3dogdare.havenjson/-name-policy/invoke.html
  doc/haven-json/com.tripl3dogdare.havenjson/deserialize.html
  doc/haven-json/com.tripl3dogdare.havenjson/index.html
  doc/haven-json/index-outline.html
  src/main/kotlin/com/tripl3dogdare/havenjson/JsonSchema.kt
  src/main/kotlin/com/tripl3dogdare/havenjson/Utils.kt
  src/test/kotlin/com/tripl3dogdare/havenjson/DeserializerTest.kt
  src/test/kotlin/com/tripl3dogdare/havenjson/NamePolicyTest.kt
Labels: enhancement, help wanted

#16 Change build.gradle to fix IDE compatibility issues
  build.gradle
Labels: bug
